# Vehicle d3 bridge configuration - Based on updated TODO.md
# Domain 0: AWSIM -> Domain 2: Autoware Vehicle d3
name: d3_bridge
from_domain: 3
to_domain: 0

topics:
  # Common topics (no remap) - shared across all vehicles
  awsim/control_cmd: # OK
    type: autoware_auto_control_msgs/msg/AckermannControlCommand
    remap: /d3/awsim/control_cmd
  
  awsim/control_mode_request_topic: # OK
    type: std_msgs/msg/Bool
    remap: /d3/awsim/control_mode_request_topic
  
  control/command/gear_cmd:
    type: autoware_auto_vehicle_msgs/msg/GearCommand
    remap: /d3/control/command/gear_cmd

  # AWSIM to autoware
  clock: # OK
    type: rosgraph_msgs/msg/Clock
    qos:
      reliability: best_effort
    reversed: True

  d3/vehicle/status/gear_status:
    type: autoware_auto_vehicle_msgs/msg/GearReport
    remap: /vehicle/status/gear_status
    reversed: True

  d3/vehicle/status/steering_status:
    type: autoware_auto_vehicle_msgs/msg/SteeringReport
    remap: /vehicle/status/steering_status
    reversed: True
  
  d3/vehicle/status/velocity_status:
    type: autoware_auto_vehicle_msgs/msg/VelocityReport
    remap: /vehicle/status/velocity_status
    reversed: True

  d3/sensing/gnss/nav_sat_fix:
    type: sensor_msgs/msg/NavSatFix
    remap: /sensing/gnss/nav_sat_fix
    reversed: True  
    
  d3/sensing/imu/imu_raw:
    type: sensor_msgs/msg/Imu
    remap: /sensing/imu/imu_raw
    reversed: True
